name: Build user service

on:
  push:
    branches:
      - dev/release-test

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and push Docker image with maven spring boot
        env:
          DOCKERHUB_USER: ${{ needs.build.outputs.dockerUser }}
          DOCKERHUB_PASSWORD: ${{ needs.build.outputs.dockerPassword }}
        run: |
          mvn spring-boot:build-image \
              -Ddocker.registry=$DOCKERHUB_USER
              -Dspring-boot.build-image.publish=true \
              -Dspring-boot.build-image.image=${{ secrets.DOCKERHUB_USER }}/mm-user-service:latest \
              -Dspring-boot.build-image.docker.username=${{ secrets.DOCKERHUB_USER }} \
              -Dspring-boot.build-image.docker.password=${{ secrets.DOCKERHUB_PASSWORD }} -DskipTests

      - name: Trigger re-deploy
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: mankis-movie-mate/mm-infrastructure
          event-type: user-service-builded
          client-payload: '{"service": "mm-user-service", "tag": "latest"}'
          token: ${{ secrets.MM_TOKEN }}
